# Generated by CMake 2.8.12.2

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" GREATER 2.4)
  # Information for CMake 2.6 and above.
  SET("LArContent_LIB_DEPENDS" "general;/usera/afm67/2020/May/CosmicJorisMay2020/PandoraSDK/lib/libPandoraSDK.so;general;/usera/afm67/2020/May/CosmicJorisMay2020/PandoraMonitoring/lib/libPandoraMonitoring.so;")
ELSE("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" GREATER 2.4)
  # Information for CMake 2.4 and lower.
  SET("LArContent_LIB_DEPENDS" "/usera/afm67/2020/May/CosmicJorisMay2020/PandoraSDK/lib/libPandoraSDK.so;/usera/afm67/2020/May/CosmicJorisMay2020/PandoraMonitoring/lib/libPandoraMonitoring.so;")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" GREATER 2.4)
